/* Virginia Explorer — content: A Growing Nation, 1783–1850 (VS.6d, VS.6e)
   Chapter 6. Reading level grades 4–5. Forced migration and Nat Turner's Rebellion are told
   plainly and factually, without graphic detail (school guidance, 2026-09-06).
*/
VA.add([
  /* ───────────── ROUTES WEST (VS.6d) ───────────── */
  { id: 'route-wilderness-road', type: 'idea', name: 'The Wilderness Road', emoji: '🥾', tagline: 'Down the Valley, through the Cumberland Gap, into Kentucky', mapRef: { kind: 'overlay', id: 'wilderness' },
    blurb: 'The <strong>Wilderness Road</strong> ran down the Shenandoah Valley, southwest along the ridges, and through the <strong>Cumberland Gap</strong> into Kentucky. Daniel Boone and thirty axmen cut it in 1775. By 1800 some <strong>200,000 people</strong> had walked or ridden through the Gap, most of them Virginians.',
    body: ['The mountains were the barrier; the gap was the door. For its first twenty years the road was too rough for wagons, so families went on foot with pack horses, carrying what they could. Kentucky was part of Virginia until 1792.'],
    facts: ['Cut by Daniel Boone, 1775', 'Through the Cumberland Gap, where Virginia, Kentucky, and Tennessee meet', 'About 200,000 travelers by 1800', 'Foot and pack horse at first; wagons after 1796'],
    standards: ['VS.6d'], related: ['place-cumberland-gap', 'region-valley', 'culture-scots-irish'] },
  { id: 'route-national-road', type: 'idea', name: 'The National Road', emoji: '🛞', tagline: 'The first federal highway, over the mountains to the Ohio River', mapRef: { kind: 'overlay', id: 'national' },
    blurb: 'Begun in 1811, the <strong>National Road</strong> was the first highway paid for by the United States government. It ran west from Cumberland, Maryland, over the Alleghenies to <strong>Wheeling</strong> on the Ohio River, then in Virginia. Wagons, stagecoaches, and herds of cattle crowded it.',
    body: ['At Wheeling, travelers switched to <strong>flatboats and steamboats</strong> on the Ohio and floated toward Ohio, Indiana, Illinois, and Missouri. A stagecoach could make Baltimore to Wheeling in about three days, a trip that had taken weeks.'],
    facts: ['Built 1811–1837', 'Cumberland, MD to Wheeling on the Ohio (Virginia until 1863)', 'First federally funded road', 'Connected to the Ohio River steamboats'],
    standards: ['VS.6d'], related: ['idea-steamboat', 'state-wv'] },
  { id: 'route-canal', type: 'idea', name: 'The James River and Kanawha Canal', emoji: '🚣', tagline: 'George Washington\'s dream of a water road to the west', mapRef: { kind: 'overlay', id: 'canal' },
    blurb: 'Rivers were the highways, but the James had rapids and the Blue Ridge in its way. Starting in 1785, with George Washington as its first president, a company dug a <strong>canal</strong> beside the James so boats could bypass the falls at Richmond and go west. By 1851 it reached Buchanan, nearly 200 miles upriver.',
    body: ['Mule-drawn <strong>canal boats</strong> carried tobacco, wheat, and flour down to Richmond and passengers up the valley. The plan was to link the James to the Kanawha and the Ohio, but the mountains won: the canal never crossed them, and railroads soon made it out of date.'],
    facts: ['Begun 1785; reached Buchanan in 1851', 'Bypassed the Fall Line rapids at Richmond', 'Mule-drawn boats carrying farm goods', 'Never reached the Ohio'],
    standards: ['VS.6d'], related: ['river-james', 'place-fall-line', 'idea-railroad'] },
  { id: 'place-wheeling', type: 'place', name: 'Wheeling', emoji: '⛵', tagline: 'Where the National Road met the Ohio River', lat: 40.064, lon: -80.721,
    blurb: '<strong>Wheeling</strong>, on the Ohio River, was Virginia\'s doorway to the West. The National Road ended here, and steamboats began. In 1863 it became the first capital of the new state of West Virginia.', body: [], facts: ['On the Ohio River; part of Virginia until 1863', 'End of the National Road'], standards: ['VS.6d'], related: ['route-national-road', 'state-wv'] },

  /* ───────────── MACHINES (VS.6d) ───────────── */
  { id: 'idea-cotton-gin', type: 'idea', name: 'The cotton gin', emoji: '⚙️', tagline: '1793 · fifty times faster, and a disaster for the enslaved', year: 1793,
    blurb: 'In 1793 Eli Whitney built a machine that pulled seeds out of cotton: the <strong>cotton gin</strong>. One worker with a gin could clean <strong>50 pounds</strong> of cotton a day instead of one. Suddenly cotton was worth growing, and planters in Georgia, Alabama, Mississippi, and Louisiana wanted more land and more workers.',
    body: ['Virginia grew little cotton, but the gin changed Virginia anyway. Deep South planters bought enslaved people, and Virginia, with worn-out tobacco land and more enslaved people than its farms needed, <strong>sold them</strong>. The cotton gin made slavery bigger, not smaller.'],
    facts: ['Eli Whitney, 1793', '1 pound a day by hand → 50 pounds with a gin', 'Cotton boom in the Deep South', 'Increased the demand for enslaved labor'],
    standards: ['VS.6d'], related: ['idea-domestic-slave-trade', 'idea-reaper'] },
  { id: 'idea-reaper', type: 'idea', name: 'The McCormick reaper', emoji: '🌾', tagline: '1831 · invented on a farm in Rockbridge County, Virginia', year: 1831,
    blurb: 'Cutting wheat by hand with a scythe was slow; a strong worker could cut about <strong>2 acres a day</strong>. In 1831, on his family\'s farm at Walnut Grove in the Shenandoah Valley, 22-year-old <strong>Cyrus McCormick</strong> built a horse-drawn <strong>reaper</strong> that cut <strong>10 to 12 acres</strong> a day.',
    body: ['The reaper let Valley farmers grow far more wheat with fewer hands, and it made the Midwest\'s huge prairie farms possible. McCormick moved his factory to Chicago in 1847 and became one of the richest men in America. The machine that fed the West was a Virginian\'s idea.'],
    facts: ['Cyrus McCormick, Walnut Grove, Rockbridge County, 1831', '2 acres a day by scythe → 10–12 acres with a reaper', 'Made big wheat farms possible', 'Factory moved to Chicago, 1847'],
    standards: ['VS.6d'], related: ['person-mccormick', 'place-walnut-grove', 'region-valley'] },
  { id: 'idea-steamboat', type: 'idea', name: 'The steamboat', emoji: '🚢', tagline: '1807 · rivers become two-way roads', year: 1807,
    blurb: 'Before steam, a boat could float <em>down</em> a river easily but had to be poled or dragged back <em>up</em>. Robert Fulton\'s <strong>steamboat</strong> (1807) changed that. By the 1820s steamboats ran on the James, the Potomac, and the Chesapeake Bay, and on the Ohio and Mississippi out west.',
    body: ['For Virginians moving west, a steamboat from Wheeling could carry a whole family and their wagon down the Ohio in days. For planters, it carried tobacco and flour to market cheaply.'],
    facts: ['Robert Fulton, 1807', 'Upstream travel became easy', 'On the James, Potomac, Bay, and Ohio by the 1820s'],
    standards: ['VS.6d'], related: ['route-national-road', 'place-wheeling', 'idea-railroad'] },
  { id: 'idea-railroad', type: 'idea', name: 'Railroads', emoji: '🚂', tagline: '1831 · Virginia\'s first railroad ran through Chesterfield County', year: 1831,
    blurb: 'Virginia\'s very first railroad opened in 1831 in <strong>Chesterfield County</strong>: the <strong>Chesterfield Railroad</strong>, 13 miles of track carrying coal from the Midlothian mines down to the James River at Manchester. Horses pulled the empty cars up; gravity rolled the full ones down.',
    body: ['Steam locomotives followed within a few years. The Richmond, Fredericksburg &amp; Potomac (1836) and Richmond &amp; Petersburg (1838) railroads cut a day\'s travel to an hour or two. Rails could go where canals could not: over mountains. By 1860 Virginia had more than 1,700 miles of track, and the railroad town of Roanoke would soon grow beside them.'],
    facts: ['Chesterfield Railroad, 1831: Virginia\'s first, Midlothian coal to the James', 'Steam locomotives by the mid-1830s', 'Over 1,700 miles of track by 1860', 'Rails crossed mountains that stopped canals'],
    standards: ['VS.6d', 'VS.9a'], related: ['place-midlothian', 'place-chesterfield', 'route-canal', 'place-roanoke'] },
  { id: 'person-mccormick', type: 'person', name: 'Cyrus McCormick', emoji: '🌾', tagline: 'Inventor of the reaper', born: '1809', died: '1884', lat: 37.93, lon: -79.35,
    blurb: '<strong>Cyrus McCormick</strong> grew up on a farm in Rockbridge County, where his father had spent years trying to build a reaping machine. In 1831 Cyrus, at 22, made one that worked, and demonstrated it in a neighbor\'s wheat field. Enslaved workers on the McCormick farm, including a man named <strong>Jo Anderson</strong>, helped build and test it.',
    body: ['McCormick moved to Chicago in 1847 to be near the prairie farms that needed his machine. His company later became International Harvester.'],
    facts: ['Born at Walnut Grove, Rockbridge County', 'Reaper demonstrated 1831', 'Jo Anderson, enslaved on the farm, helped build it'],
    standards: ['VS.6d'], related: ['idea-reaper', 'place-walnut-grove'] },
  { id: 'place-walnut-grove', type: 'place', name: 'Walnut Grove (McCormick Farm)', emoji: '🏡', tagline: 'Birthplace of the reaper, Rockbridge County', lat: 37.93, lon: -79.35,
    blurb: '<strong>Walnut Grove</strong>, the McCormick family farm in the Valley near Lexington, is where the first reaper was built and tested in 1831. The blacksmith shop and gristmill still stand.', body: [], facts: ['Rockbridge County, Valley and Ridge region', 'First reaper, 1831'], standards: ['VS.6d'], related: ['idea-reaper', 'person-mccormick', 'region-valley'] },
  { id: 'place-midlothian', type: 'place', name: 'Midlothian coal mines', emoji: '⛏️', tagline: 'Chesterfield County · America\'s first coal mines and Virginia\'s first railroad', lat: 37.505, lon: -77.65,
    blurb: 'Coal was dug at <strong>Midlothian</strong> in Chesterfield County as early as the 1700s, the first commercial coal mines in America. In 1831 the <strong>Chesterfield Railroad</strong> opened to carry that coal 13 miles to the James River. It was the first railroad in Virginia, right here in our county.',
    body: [], facts: ['Chesterfield County', 'First commercial coal mines in America', 'Virginia\'s first railroad, 1831'], standards: ['VS.6d'], related: ['idea-railroad', 'place-chesterfield'] },

  /* ───────────── MIGRATION, FORCED AND FREE (VS.6d) ───────────── */
  { id: 'idea-migration-west', type: 'idea', name: 'Virginians go west', emoji: '🛒', tagline: 'Worn-out land behind them, cheap land ahead',
    blurb: 'After the Revolution, Virginians left in huge numbers. Tobacco had <strong>worn out</strong> the soil of the Tidewater and Piedmont. Beyond the mountains, land was cheap and fresh. Families packed wagons and went to Kentucky, Tennessee, Ohio, Indiana, Missouri, and later Texas.',
    body: ['In 1790 Virginia was the <strong>biggest state</strong>, with nearly one in five Americans. By 1860 it had slipped to fifth. Seven presidents\' worth of Virginians ended up governing other states; more Kentuckians and Tennesseans were born in Virginia than anywhere else. <strong>Migration</strong> like this, chosen by the people who moved, is called voluntary.'],
    facts: ['Causes: worn-out soil, cheap western land, new roads and rivers', 'Virginia: largest state in 1790, fifth by 1860', 'Destinations: Kentucky, Tennessee, Ohio, Missouri, Texas', 'Voluntary migration: people chose to go'],
    standards: ['VS.6d'], related: ['route-wilderness-road', 'route-national-road', 'idea-domestic-slave-trade'] },
  { id: 'idea-domestic-slave-trade', type: 'idea', name: 'Sold south: the forced migration', emoji: '⛓️', tagline: 'Virginia became the biggest seller of enslaved people in the country',
    blurb: 'Not everyone who left Virginia chose to. Between about 1790 and 1860, Virginia planters <strong>sold</strong> more than <strong>300,000 enslaved people</strong> to the cotton and sugar plantations of the Deep South. This was <strong>forced migration</strong>. Families were split apart, often forever: parents from children, husbands from wives.',
    body: [
      'Why? Tobacco land was worn out, so Virginia planters had more enslaved workers than they needed. The cotton gin made Deep South planters hungry for workers. Selling people became one of Virginia\'s biggest businesses. <strong>Richmond</strong> was the largest slave market in the Upper South; people were auctioned in Shockoe Bottom a few blocks from the State Capitol.',
      'Enslaved people walked south in chained groups called coffles, or were shipped from Norfolk and Alexandria to New Orleans. Historians call this the "Second Middle Passage." It moved more people than the ocean trade ever brought to the colonies.'
    ],
    facts: ['More than 300,000 people sold out of Virginia, 1790–1860', 'Richmond: largest slave market in the Upper South', 'Families permanently separated', 'Forced migration: no one chose to go'],
    standards: ['VS.6d', 'VS.6e'], related: ['idea-cotton-gin', 'place-shockoe', 'idea-migration-west', 'idea-everyday-resistance'] },
  { id: 'place-shockoe', type: 'place', name: 'Shockoe Bottom, Richmond', emoji: '🏚️', tagline: 'Site of the slave auctions and Lumpkin\'s Jail', lat: 37.5335, lon: -77.4300,
    blurb: '<strong>Shockoe Bottom</strong>, the low ground along the James in downtown Richmond, held dozens of auction houses and slave jails in the 1840s and 1850s. Tens of thousands of people were sold here and marched to ships or trains bound south. Today a memorial and the site of Lumpkin\'s Jail, "the Devil\'s Half Acre," mark the place.',
    body: [], facts: ['Downtown Richmond, below the Capitol', 'Largest slave market in the Upper South', 'Now a memorial site'], standards: ['VS.6d'], related: ['idea-domestic-slave-trade', 'place-richmond'] },

  /* ───────────── RESISTANCE AND NAT TURNER (VS.6e) ───────────── */
  { id: 'idea-everyday-resistance', type: 'idea', name: 'Everyday resistance', emoji: '🤫', tagline: 'Small acts, every day, to push back',
    blurb: 'Enslaved people could not vote, sue, or leave. But they <strong>resisted</strong> in ways that were hard to punish: working slowly, "accidentally" breaking tools, pretending to be sick or not to understand, running away for a few days to visit family or protest a cruel overseer. They kept their own music, stories, and faith alive, and some learned to read in secret even after it became illegal.',
    body: ['Open rebellion was rare because it was nearly hopeless: slaveholders had the militia, the guns, and the law. Everyday resistance was how most enslaved people held on to some control over their own lives, and how they kept their families and culture together.'],
    facts: ['Working slowly, breaking tools, pretending illness', 'Running away for short periods', 'Secret reading, church, music, and stories', 'Open rebellion was rare and dangerous'],
    standards: ['VS.6e'], related: ['person-nat-turner', 'water-dismal-swamp', 'culture-african'] },
  { id: 'person-nat-turner', type: 'person', name: 'Nat Turner', emoji: '📖', tagline: 'Enslaved preacher who led the 1831 rebellion', born: '1800', died: '1831', lat: 36.78, lon: -77.15,
    blurb: '<strong>Nat Turner</strong> was born enslaved in <strong>Southampton County</strong> in 1800. He learned to read as a child, knew the Bible deeply, and became a preacher to other enslaved people. He came to believe God had chosen him to strike against slavery.',
    body: [
      'On the night of <strong>August 21, 1831</strong>, Turner and a small group began moving from farm to farm, killing the white families they found and gathering more followers, about 70 in all. In less than two days they killed about 60 white people, many of them children. Their goal was the county seat, Jerusalem (now Courtland). Militia and armed neighbors stopped them before they reached it.',
      'Turner hid in the woods for two months, was captured on October 30, put on trial, and executed on November 11, 1831. Before he died he dictated his story, published as <em>The Confessions of Nat Turner</em>.'
    ],
    facts: ['Born enslaved, Southampton County, 1800', 'Preacher who could read', 'Led the rebellion of August 21–22, 1831', 'Captured October 30; executed November 11, 1831'],
    standards: ['VS.6e'], related: ['event-turner-rebellion-1831', 'event-turner-aftermath-1831', 'place-southampton', 'idea-everyday-resistance'] },
  { id: 'place-southampton', type: 'place', name: 'Southampton County', emoji: '📍', tagline: 'Where the rebellion happened, August 1831', lat: 36.72, lon: -77.10,
    blurb: '<strong>Southampton County</strong> is in the southern Coastal Plain, on the North Carolina line near the Great Dismal Swamp. In 1831 it was farm country where enslaved people outnumbered white residents. The rebellion moved across about 20 miles of its farms toward the county seat, Jerusalem, now called <strong>Courtland</strong>.',
    body: [], facts: ['Southern Coastal Plain, near the NC line', 'County seat: Jerusalem, now Courtland', 'Also home of the Nottoway people'], standards: ['VS.6e'], related: ['person-nat-turner', 'tribe-cheroenhaka', 'water-dismal-swamp'] },
  { id: 'event-turner-rebellion-1831', type: 'event', name: 'Nat Turner\'s Rebellion', short: 'The rebellion', emoji: '🔥', year: 1831, month: 8,
    blurb: 'August 21–22, 1831: Nat Turner and about 70 followers move across Southampton County, farm to farm, killing about 60 white people. Militia from the surrounding counties, and soldiers from Fort Monroe, put the rebellion down within two days. It is the deadliest slave rebellion in American history.',
    body: [], facts: ['August 21–22, 1831', 'About 70 rebels; about 60 white people killed', 'Stopped within two days'], standards: ['VS.6e'], related: ['person-nat-turner', 'place-southampton'] },
  { id: 'event-turner-aftermath-1831', type: 'event', name: 'Reprisals and the trial', short: 'Aftermath', emoji: '⚖️', year: 1831, month: 11,
    blurb: 'In the weeks after, white mobs and militia killed dozens of Black people across the region, most of whom had nothing to do with the rebellion. Courts tried about 50 people; about 20 were executed. Turner himself was captured on October 30 and hanged on November 11.',
    body: [], facts: ['Dozens of Black people killed in reprisals, many innocent', 'About 20 executed after trials', 'Turner executed November 11, 1831'], standards: ['VS.6e'], related: ['person-nat-turner', 'event-slave-laws-1832'] },
  { id: 'event-slave-laws-1832', type: 'event', name: 'Virginia tightens the laws', short: 'Harsher laws', emoji: '📕', year: 1832, month: 3,
    blurb: 'Frightened by the rebellion, the General Assembly passed harsher laws in 1832: it became illegal to teach any Black person, enslaved or free, to read or write; Black preachers were banned; enslaved people could not gather without a white person present; free Black Virginians lost more rights. Slaveholders decided that keeping people ignorant and separated was the way to stay safe.',
    body: [], facts: ['Illegal to teach Black Virginians to read', 'Black preachers banned', 'Gatherings restricted', 'Free Black people lost rights'], standards: ['VS.6e'], related: ['event-va-debate-1832', 'person-nat-turner'] },
  { id: 'event-va-debate-1832', type: 'event', name: 'The Assembly debates ending slavery, and votes no', short: 'The great debate', emoji: '🏛️', year: 1832, month: 1,
    blurb: 'In January 1832, shaken by Southampton, the Virginia General Assembly openly debated whether to end slavery gradually. For two weeks it was the biggest question in the state. In the end the Assembly voted <strong>not</strong> to act. It was the last time a Southern legislature seriously considered abolition before the Civil War.',
    body: ['After 1832 the argument over slavery only grew sharper, in Virginia and across the country. The road from Southampton runs, in a way, to Harpers Ferry and the Civil War.'],
    facts: ['January 1832', 'Debated gradual abolition; voted no', 'Tensions over slavery grew afterward'], standards: ['VS.6e'], related: ['event-slave-laws-1832', 'event-turner-rebellion-1831'] },
]);
